Create: mapper dt ,controller  with crud and search, exception, mvc
ArtemMakovskyy/onlineBookStore pull request #1
Opened 2023-08-16 11:59 UTC by ArtemMakovskyy

2023-08-16 14:10 UTC, aaananas approved these changes

2023-08-17 12:02 UTC, Rommelua requested changes

2023-08-17 12:02 UTC, Rommelua commented on src/main/java/book_store/dto/CreateBookRequestDto.java
> +    private BigDecimal price;
@NotNull

2023-08-17 12:02 UTC, Rommelua commented on src/main/java/book_store/model/Book.java
> +@SQLDelete(sql = "UPDATE books SET is_deleted = 1 WHERE id=?")
```suggestion
@SQLDelete(sql = "UPDATE books SET is_deleted = true WHERE id=?")
```

2023-08-18 09:36 UTC, Rommelua requested changes

2023-08-18 09:36 UTC, Rommelua commented on src/main/java/online/book/store/model/Book.java
> +@Data
do not use @Data in entity classes

2023-08-18 09:36 UTC, Rommelua commented on src/main/java/online/book/store/repository/book/spec/PriceSpecificationProvider.java
> +                root.get(PRICE_KEY).in(Arrays.stream(params).toArray());
Can we use "in" for the price? We should have low and high boundaries.

2023-08-18 09:36 UTC, Rommelua commented on src/main/java/online/book/store/repository/book/spec/TitleSpecificationProvider.java
> +                -> root.get(TITLE_KEY).in(Arrays.stream(params).toArray());
let`s use "like" logic here

2023-08-18 15:33 UTC, sokimaaa commented on src/main/java/online/book/store/OnlineBookStoreApplication.java
> +        System.out.println("API Documentation Overview - " + SWAGGER_LINK);
I suggest using `Logging` instead of `System.out`.

2023-08-18 15:36 UTC, sokimaaa commented on src/main/java/online/book/store/controller/BookController.java
> +        return bookService.findAll(pageable);
let's return `Page<BookDto>` instead of `List<BookDto>`. 
let's provide precise parameters for the client, e.g. pageNumber, sortingBy, et cetera.

2023-08-18 15:37 UTC, sokimaaa commented on src/main/java/online/book/store/controller/BookController.java
> +    public List<BookDto> searchBooks(BookSearchParameters searchParameters) {
let's return `Page<BookDto>` instead of `List<BookDto>`

2023-08-19 15:28 UTC, aaananas approved these changes

2023-09-02 15:26 UTC, aaananas approved these changes

2023-09-15 17:42 UTC, sokimaaa requested changes

2023-09-15 17:42 UTC, sokimaaa commented on src/main/java/online/book/store/OnlineBookStoreApplication.java
> +    //    private final ShoppingCartRepository shoppingCartRepository;
remove unused comments

2023-09-15 17:42 UTC, sokimaaa commented on src/main/java/online/book/store/OnlineBookStoreApplication.java
> +    }
this code is doing something? if not should be removed

2023-09-15 17:42 UTC, sokimaaa commented on src/main/java/online/book/store/dto/cart/item/AddBookToTheShoppingCartDto.java
> +    private int quantity;
why validation annotations are not present here? e.g.
@NotNull, @Min

2023-09-15 17:42 UTC, sokimaaa commented on src/main/java/online/book/store/controller/ShoppingCartController.java
> +            @RequestBody AddBookToTheShoppingCartDto addBookDto) {
why do not validate `addBookDto`?

2023-09-15 17:42 UTC, sokimaaa commented on src/main/java/online/book/store/controller/ShoppingCartController.java
> +    public AddBookToTheShoppingCartDto addBookToTheShoppingCart(
AddBookToTheShoppingCartDto is the bad response for the POST method.
Should be returned right return status code.

2023-09-15 17:42 UTC, sokimaaa commented on src/main/java/online/book/store/model/Category.java
> +                && Objects.equals(description, category.description);
```
return Objects.equals(id, category.id)
                && Objects.equals(name, category.name);
```

2023-09-18 10:55 UTC, merged