Add shopping cart model
ArtemMakovskyy/onlineBookStore pull request #2
Opened 2023-09-15 16:53 UTC by ArtemMakovskyy

2023-09-15 17:43 UTC, sokimaaa commented on src/main/java/online/book/store/OnlineBookStoreApplication.java
> +    //    private final ShoppingCartRepository shoppingCartRepository;
remove unused comments

2023-09-15 17:44 UTC, sokimaaa commented on src/main/java/online/book/store/model/Category.java
> +                && Objects.equals(description, category.description);
```suggestion
return Objects.equals(id, category.id)
                && Objects.equals(name, category.name);
```

2023-09-15 17:45 UTC, sokimaaa commented on src/main/java/online/book/store/controller/ShoppingCartController.java
> +            @RequestBody AddBookToTheShoppingCartDto addBookDto) {
why do not validate addBookDto?

2023-09-15 17:45 UTC, sokimaaa commented on src/main/java/online/book/store/dto/cart/item/AddBookToTheShoppingCartDto.java
> +    private int quantity;
why validation annotations are not present here? e.g.
https://github.com/NotNull, @min

2023-09-15 17:46 UTC, sokimaaa commented on src/main/java/online/book/store/OnlineBookStoreApplication.java
> +    }
this code is doing something? if not should be removed

2023-09-16 15:48 UTC, aaananas requested changes

2023-09-16 15:48 UTC, aaananas commented on src/main/java/online/book/store/controller/AuthenticationController.java
> +        System.out.println(requestDto);
if you want to output something - use logs

in this case, it is not recommended, that you expose passwords in logs. It is sensitive information

2023-09-16 15:48 UTC, aaananas commented on src/main/java/online/book/store/mapper/BookMapper.java
> +        }
```suggestion
            final Set<Category> categories = new HashSet<>();
            for (Long id : createDto.getCategories()) {
                Category category = new Category(id);
                categories.add(category);
            }
            book.setCategories(categories);
```

2023-09-22 20:41 UTC, closed without merging