Add order model
ArtemMakovskyy/onlineBookStore pull request #4
Opened 2023-09-22 20:42 UTC by ArtemMakovskyy

2023-09-23 15:19 UTC, aaananas requested changes

2023-09-23 15:19 UTC, aaananas commented on src/main/java/online/book/store/service/impl/OrderServiceImpl.java
> +        return new Sort.Order(Sort.Direction.valueOf(direction), property);
Lets move this to a separate class, SortUtil

2023-09-24 09:11 UTC, sokimaaa commented on src/main/java/online/book/store/util/SortUtil.java
> +    public static Sort.Order parseSortOrder(String sort) {
any Util classes should 
1) be final
2) have all static methods
3) not be accessible to instantiate (e.g. private constructor)

2023-09-25 10:40 UTC, Rommelua approved these changes

2023-09-25 10:40 UTC, Rommelua commented on src/main/java/online/book/store/model/Book.java
> +                && Objects.equals(coverImage, book.coverImage);
```suggestion
        return Objects.equals(isbn, book.isbn);
```

2023-10-06 05:34 UTC, closed without merging